blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: {{ community.url }}
    about: Suggest an idea for this project
  - name: Question / Problem
    url: {{ community.url }}
    about: Questions and problems with n8n
  - name: n8n Security Vulnerability
    url: {{ site.url }}/legal/#vulnerability
    about: Learn about our Vulnerability Disclosure Policy